repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^static/launch/assets/
      - id: end-of-file-fixer
      - id: check-yaml
      - id: fix-encoding-pragma
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=119"]
  -   repo: https://github.com/PyCQA/flake8
      rev: 7.1.0
      hooks:
        - id: flake8
  - repo: local
    hooks:
      - id: unit test
        name: pytest
        entry: poetry run pytest .
        types: [python]
        language: system
        pass_filenames: false
        always_run: true
